### ISSUE TITLE
Safeguard default not working in all cases

### ISSUE THREAD

**Issue by FlyingLemming** [stfnhmplr/homebridge-homee#14]
While merging my last pull request containing the "safeguard", you made a few changes to my proposal. Instead of having a config option to switch the safeguard on or off, you made it the default (which I fully support) and removed the config option. However, you only changed it for the case when homebridge is not able to receive devices/homeegrams due to a time-out (lines 63/64). The other case where no devices/homeegrams can be retrieved due to an incorrect group name (lines 139-141) still requires the safeGuard config parameter, defaulted to false in line 38 and not documented anymore.
Is this behaviour intended or did you just miss that second case?

**Comment by stfnhmplr** [comment]
Implementing Safeguard as a standard made the most sense. At least as long as this plugin doesn't use the Homebridge API.
This behavior is not intended. I simply overlooked that. I can't imagine anyone changing the group name afterwards, but I'll change it right now.
