### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mtressl** [stfnhmplr/homebridge-homee#18]
Since we are at it another WARNING caused by the plugin, but it might be more serious since it references a DeprecationWarning:

`[1/11/2020, 6:09:01 PM] [Homee] Not connected to homee. Retrying...
(node:3639) UnhandledPromiseRejectionWarning: Error: Cannot connect
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-denon-v2/node_modules/telnet-client/lib/index.js:79:25)
    at Object.onceWrapper (events.js:312:28)
    at Socket.emit (events.js:223:5)
    at Socket._onTimeout (net.js:474:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:3639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3639) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Thanks for looking into this.

**Comment by mtressl** [comment]
Any update?

**Comment by stfnhmplr** [comment]
This issue is not related to this plugin. This is caused by *homebridge-denon-v2*.
see `/homebridge/node_modules/homebridge-denon-v2/node_modules/telnet-client/lib/index.js:79:25`

**Comment by mtressl** [comment]
Thanks, and sorry for the confusion.
