### ISSUE TITLE
Would this plugin work with a Hormann Garage door?

### ISSUE THREAD

**Issue by EdwardChamberlain** [stfnhmplr/homebridge-homee#23]
It appears that Hormann are using the Homee platform for their smart doors. If the door is correctly added in homee would this plugin be able to expose it to apple HomeKit? 

https://www.hormann.co.uk/home-owners-and-renovators/smart-home/

**Comment by stfnhmplr** [comment]
Unfortunately, I can't try this myself and haven't heard anything about it yet. Maybe you better ask the question in the [homee community forum](https://community.hom.ee). Maybe someone has already tried it there.
